### ISSUE TITLE
[TASK] Get this project package published to the AUR

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#102]
## Task Context

Given that initial setup steps have been completed on this project to get it on the AUR, this task is to get the project package officially published to the AUR as `mya-git`.

## Acceptance Criteria

The acceptance criteria for this task is to manually get the project published to the AUR.

## Additional Context

Feel free to tag @jmakhack in the comments of this issue with any questions or to request any info if needed.
Some research may need to be done regarding the AUR in order to complete and close out this issue.

Please read through the [Contributing to the Project](../../CONTRIBUTING.md) document before working on this project.

**Comment by jmakhack** [comment]
@npranav7619, let me know if you would like to be assigned to this task since I believe you have already started taking a look into it.

**Comment by npranav7619** [comment]
Yes Please :)

**Comment by npranav7619** [comment]
https://aur.archlinux.org/packages/mya-git

done :)

**Comment by jmakhack** [comment]
Thanks @npranav7619 , this is great!

Can you include any steps/instructions on how you got this published?

**Comment by jmakhack** [comment]
In addition, is it possible to change the version number to 1.0 on the aur?

At the moment, it seems to be set to a random string of characters.

**Comment by npranav7619** [comment]
To publish a package on **AUR repository**

1. Create an account on AUR 
2. Generate ssh key  using ssh-keygen and upload it to your account
Make sure to correctly set the config file from Arch-wiki
3. Clone an empty repository from AUR  with the name you want your package to have
 eg) git clone `aur@aur.archlinux.org/nameoftherepo.git`
4. Add the PKGBUILD file and .SRCINFO file from your repo
5. Commit changes 

and voila its done :)

**Comment by npranav7619** [comment]
> In addition, is it possible to change the version number to 1.0 on the aur?
> 
> At the moment, it seems to be set to a random string of characters.

That is not random string of characters  its was generated because its a git package
It was recommended to do that if the package is built with git as the base

**Comment by jmakhack** [comment]
> > In addition, is it possible to change the version number to 1.0 on the aur?
> > 
> > At the moment, it seems to be set to a random string of characters.
> 
> That is not random string of characters  its was generated because its a git package
> It was recommended to do that if the package is built with git as the base 
> 
> 

Ah interesting, thanks for clarifying!
