### ISSUE TITLE
[TASK] Fix unit testing issues for mya.c

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#29]
## Task Context
The work to start adding unit tests to this project began in #13.
A pull request was opened here: https://github.com/jmakhack/myanimelist-cli/pull/23

However, though a lot of work went into adding these unit tests, the work was never completed. There are currently issues with getting the tests to run and the project to build successfully.

This task is to work off the branch and code already present on that pull request and fix the issues so that:

1. The project code can compile and build successfully
2. The unit tests added can be successfully run

**Comment by kana800** [comment]
Hello there !
I am interested in writing some unit tests; Let me know if this issue is available

**Comment by jmakhack** [comment]
Hey @kana800, you can work on this issue if you'd like! I've assigned it to you.

There currently isn't any unit testing framework set up so this task may be a bit tricky. Let me know if you need any help on this. There was some initial work done in #23 but was never completed.

**Comment by kana800** [comment]
Hey @jmakhack I checked out the #23; There was some [workdone](https://github.com/jmakhack/myanimelist-cli/pull/23/commits/be533ca8dc1f79c455375f2da4186e32ee0df37c#diff8dec81c3f40f538b83383f1969ab19ec069aa25c3f902af4bd6ca9468480d29f]) by @TBeeren do you think he going to continue the #23? ;

**Comment by jmakhack** [comment]
@kana800, there have been some changes in the project code since then so no, but it is a good starting point/reference to work off of if needed.

**Comment by jmakhack** [comment]
Closing this for now and will potentially open a new issue for unit testing with updated details now that the build process for this project has changed.
