### ISSUE TITLE
[TASK] Fix code style issues in contributing docs 

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#30]
## Task Context

The Codacy software which helps to determine the project's code quality is currently reporting a B score for this project.
This is mostly due in part to code style issues it is reporting for the contributing docs which is written in Markdown.

Click on the following link to view the code style issues that needs to be fixed: https://app.codacy.com/gh/jmakhack/myanimelist-cli/issues?categoryType=CodeStyle

## Acceptance Criteria
1. Fix the 9 code style issues mentioned in the Codacy link (while not adding new ones)
2. Rename `CONTRIBUTION.md` to `CONTRIBUTING.md` which is the GitHub standard

## Additional Context

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[![Discord](https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA)](https://discord.gg/RTgxfFW9mS)

**Comment by Nikhil-1503** [comment]
Hey,
I would love to work on this.

**Comment by jmakhack** [comment]
Go for it @Nikhil-1503! :)
