### ISSUE TITLE
[TASK] Fix code style issues in task template

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#32]
## Task Context

With the introduction of a new task template, there was also a code style issue added.

This task is to remove that code style issue in an effort to improve the overall quality of the project files.

## Acceptance Criteria

Fix the Codacy reported issue here: https://app.codacy.com/gh/jmakhack/myanimelist-cli/file/76787783830/issues/source?bid=22863233&fileBranchId=22863233#l4

## Additional Context

The task template can be found here: [task.md](https://github.com/jmakhack/myanimelist-cli/blob/master/.github/ISSUE_TEMPLATE/task.md)

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[![Discord](https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA)](https://discord.gg/RTgxfFW9mS)

**Comment by VividhPandey003** [comment]
Hey. I am a beginner to Open Source and really looking forward to contribute. Could you please assign this issue to me under Hacktoberfest

**Comment by jmakhack** [comment]
@VividhPandey003, it's all yours! Just make sure to wait until October 1st before opening your pull request.
If you have any questions, joining the [Discord](https://discord.gg/RTgxfFW9mS) community is the way to go!
