### ISSUE TITLE
[TASK] Add instructions on how to install from source

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#33]
## Task Context

Currently, there are no installation instructions for this project.

This task is to add the installation instructions to the project's README for different operating systems.

## Acceptance Criteria

Add instructions on how to install this program from source for the following operating systems:
1. Windows
2. MacOS
3. Linux

Place these instructions between the `Example` and `Code of Conduct` sections of the README.

## Additional Context

For an idea of what commands are needed to install this program on different operating systems, you can take a look at the installation instructions for https://github.com/pystardust/ani-cli. The installation from source instructions for Windows, MacOS, and Linux should be very similar for this project.

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[![Discord](https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA)](https://discord.gg/RTgxfFW9mS)

**Comment by VividhPandey003** [comment]
Hey, I am a beginner to Open Source and really looking forward to contribute to this repo. Could you please assign this issue to me

**Comment by jmakhack** [comment]
Sure @VividhPandey003! It's assigned to you now.
Just let me know if you have any questions.

**Comment by VividhPandey003** [comment]
Hey @jmakhack I currently have a MacOS. Are the install instructions for _myanimelist-cli_ same as the reference doc you shared. Also can I discuss this issue with you on Discord or here only works fine

**Comment by jmakhack** [comment]
Hey @VividhPandey003, Discord is preferable for discussions. I'll ping you there :)
