### ISSUE TITLE
[TASK] Add automation to set assignees on pull requests

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#42]
## Task Context

At the moment, pull request assignees have to be set manually either while a pull request is being created or after it has already been created. This adds a bit of unnecessary manual labor that should be able to be easily solved with some level of automation.

## Acceptance Criteria / Goals

Whan a new pull request is opened the following should be automated:
1. The assignee is set to the Github user who opened the pull request

## Additional Context

See https://github.com/jmakhack/hydrate-reminder/pull/235/files for how this was accomplished in a separate project. The same Github action should be able to be used for this project.

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[![Discord](https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA)](https://discord.gg/RTgxfFW9mS)

**Comment by AdityaJ7** [comment]
hi @jmakhack can i pick this one up?

**Comment by jmakhack** [comment]
Go for it @AdityaJ7! I just assigned it to you.

**Comment by AdityaJ7** [comment]
created a pr for the same @jmakhack
