### ISSUE TITLE
[TASK] Add automation to set reviewers on pull requests

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#46]
## Task Context

At the moment, pull request reviewers have to be set manually either while a pull request is being created or after it has already been created. This adds a bit of unnecessary manual labor that should be able to be easily solved with some level of automation.

## Acceptance Criteria

Whan a new pull request is opened the two following item should be automated:
-  The reviewer is set to @jmakhack

## Additional Context

Here is a good reference for how this was accomplished in a separate project: https://github.com/jmakhack/hydrate-reminder/pull/235

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[![Discord](https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA)](https://discord.gg/RTgxfFW9mS)

**Comment by galbwe** [comment]
Hello! Can I work on this issue?

**Comment by jmakhack** [comment]
Go for it @galbwe! :)

**Comment by galbwe** [comment]
I think all that needs to be done here is update [CODEOWNERS](https://github.com/jmakhack/myanimelist-cli/blob/master/.github/CODEOWNERS). It is missing a file pattern.

See also https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners
