### ISSUE TITLE
[BUG] Remove unnecessary underscores in first line of output

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#49]
## Bug Description

When displaying a user's `on hold` and `plan to watch` lists using the `-h` and `-p` options respectively, the first line of the output contains unwanted underscores. See screenshots below:

<img width="817" alt="Screen Shot 2022-10-08 at 4 57 11 AM" src="https://user-images.githubusercontent.com/1442227/194706353-5c636b7c-773d-4e37-8666-c4f3df7bc77d.png">
<img width="822" alt="Screen Shot 2022-10-08 at 4 57 40 AM" src="https://user-images.githubusercontent.com/1442227/194706356-af57dc29-8aa0-495b-86a8-b51637a580f6.png">

## Expected Behavior

Instead of `on_hold` and `plan_to_watch`, the first line of the output should print `on hold` and `plan to watch` respectively.

## Environment

Operating System: Ubuntu 22.04

## Additional Context

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[![Discord](https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA)](https://discord.gg/RTgxfFW9mS)

**Comment by DHRUVKHANDELWAL00** [comment]
hey @jmakhack ,please assign it to me.

**Comment by jmakhack** [comment]
go for it @DHRUVKHANDELWAL00! :)

**Comment by jmakhack** [comment]
Hi @DHRUVKHANDELWAL00, just checking in. Are you still working on this issue?

**Comment by Godson-Gnanaraj** [comment]
@jmakhack Please assign this issue to me.
