### ISSUE TITLE
[BUG] Fix first line of output when -a option is used

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#50]
## Bug Description

When using the `-a` option to display a user's entire list of anime, the first line of output displays a blank followed by `<num> anime`. See screenshot below:
<img width="822" alt="Screen Shot 2022-10-08 at 12 02 15 AM" src="https://user-images.githubusercontent.com/1442227/194706593-e877f381-c80f-4a0a-b88d-efa7dbd3e259.png">

## Expected Behavior

The first line of the output when using the `-a` option should be displayed as `all <num> anime`.

## Environment

Operating System: Ubuntu 22.04

## Additional Context

For reference, the first line of output usually displays like the following:
<img width="820" alt="Screen Shot 2022-10-08 at 4 56 52 AM" src="https://user-images.githubusercontent.com/1442227/194706585-057c81e9-72d0-46cb-b441-dced1800bb50.png">

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[![Discord](https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA)](https://discord.gg/RTgxfFW9mS)

**Comment by techsnap** [comment]
Hi, I would like to work on this issue.

**Comment by jmakhack** [comment]
Hi @techsnap, go for it! Let me know if you have any questions :)

**Comment by Godson-Gnanaraj** [comment]
@jmakhack Can I take this up?

**Comment by jmakhack** [comment]
Hi @techsnap, just checking in. Are you still working on this issue?

**Comment by techsnap** [comment]
Hello @jmakhack, I am not working on this. You can assign this to @Godson-Gnanaraj
