### ISSUE TITLE
[BUG] Display more meaningful error message when Client ID not provided

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#51]
## Bug Description

This project requires a MyAnimeList Client ID in order to fetch the required data from the API.
https://github.com/jmakhack/myanimelist-cli/blob/61f91c22a837838b138ea0c35b8c947eda66b1aa/src/mya.c#L12

When the Client ID is not provided, the following misleading error is displayed:
<img width="826" alt="Screen Shot 2022-10-08 at 6 52 14 PM" src="https://user-images.githubusercontent.com/1442227/194733934-4fa35c02-6445-4750-873c-fba4e0b0b9b2.png">

## Expected Behavior

Instead of a `User not found` error message, the expected behavior is that a more meaningful error message would be displayed such as `Client ID has not been provided`.

## Environment

Operating System: Ubuntu 22.04

## Additional Context

Note: This issue is to only fix the issue where the Client ID has not been provided. A separate issue will be created to handle the case where an invalid Client ID has been provided.

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[![Discord](https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA)](https://discord.gg/RTgxfFW9mS)

**Comment by Sakshi-75** [comment]
Hi @jmakhack ,
Can I work on this?

**Comment by jmakhack** [comment]
Go for it @Sakshi-75!
