### ISSUE TITLE
[BUG] Misleading error message when providing an invalid Client ID

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#55]
## Bug Description

When an invalid Client ID is used in the project, the following error message is displayed:
<img width="817" alt="Screen Shot 2022-10-08 at 11 18 48 PM" src="https://user-images.githubusercontent.com/1442227/194743463-f71e987e-448d-4e6c-a04c-bbc8cf886e46.png">

## Expected Behavior

The expected behavior is that when an invalid Client ID is given, a proper error message is displayed. It should be something like: `Invalid Client ID provided`.

## Environment

Operating System: Ubuntu 22.04

## Additional Context

See: https://myanimelist.net/apiconfig/references/api/v2#section/Common-status-codes

**Comment by Aman0307** [comment]
@jmakhack Would I be able to contribute or setup the project on windows 11 OS??

**Comment by jmakhack** [comment]
@Aman0307 It may be possible but I have not tested how project setup would work on Windows.
I wouldn't be able to help with the setup process on Windows besides spinning up a Linux virtual machine.

**Comment by sameersecond** [comment]
Hi,
Can I work on this?

**Comment by jmakhack** [comment]
@sameersecond, missed your comment before. Let me know if you're still interested in this issue.

**Comment by sameersecond** [comment]
Hi,
I have my exams going on currently so will be off.
If no one else takes it up by Monday, I'll be interested.

**Comment by jmakhack** [comment]
No worries @sameersecond. Good luck on your exams!

**Comment by sameersecond** [comment]
Hi @jmakhack, I am free now and can work on this issue

**Comment by jmakhack** [comment]
Closing this as it may no longer be relevant as part of #99.
