### ISSUE TITLE
[FEATURE] Add option to limit results to SFW anime

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#56]
## Is your feature request related to a problem? Please describe

By default, the program displays all anime for a particular user regardless of SFW/NSFW status. Sometimes, only the SFW results are wanted.

## Describe the solution you'd like

Add a new option `-s` which will filter out the results to only show SFW results.

## Additional context

See: https://myanimelist.net/apiconfig/references/api/v2#section/Common-parameters

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[![Discord](https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA)](https://discord.gg/RTgxfFW9mS)

**Comment by sameersecond** [comment]
Hi,
Can I try this out. I have a rough idea on what to do.
