### ISSUE TITLE
[TASK] Fix potential security problem in sprintf call

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#57]
## Task Context

The following Codacy link contains the description of the potential security issue:

https://app.codacy.com/gh/jmakhack/myanimelist-cli/issues?bid=22863233&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJTZWN1cml0eSJdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6WyI2NTAzIl19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltdfV0=

## Acceptance Criteria

The acceptance criteria for this task is to adjust the code to fix the potential security issue with the sprintf call.

## Additional Context

For more info about CWE-120: https://cwe.mitre.org/data/definitions/120.html

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[![Discord](https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA)](https://discord.gg/RTgxfFW9mS)

**Comment by sameersecond** [comment]
Hi,
Can I work on this issue?

**Comment by jmakhack** [comment]
go for it @sameersecond! :)

**Comment by sameersecond** [comment]
I think Ahmed has already made the changes in #59.
