### ISSUE TITLE
[FEATURE] Set count display color to pink

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#67]
## Is your feature request related to a problem? Please describe

Right now, the count display and the anime list all appears in the same color. It would be nice to have some color distinction between them.

## Describe the solution you'd like

The count display (i.e. `completed 24 anime`) should be outputted pink in color. The anime list should remain unchanged in color.

## Describe any possible alternatives

Any other colors for the count display are possible alternatives. Another possible alternative is to keep the count display the same color and instead change the color of the anime list instead.

## Additional context

Please read through the [Contributing to the Project](../../CONTRIBUTING.md) document before working on this project.

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[![Discord](https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA)](https://discord.gg/RTgxfFW9mS)

**Comment by flying-solo** [comment]
@jmakhack i would like to work on this kindly assign this task to me

**Comment by jmakhack** [comment]
Go for it @flying-solo :)

**Comment by jmakhack** [comment]
Hi @flying-solo, just checking in. Are you still working on this issue?

**Comment by Godson-Gnanaraj** [comment]
@jmakhack could you please assign it to me?
