### ISSUE TITLE
[TASK] Migrate the project over to use CMake

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#71]
## Task Context

Currently the project is using a basic Makefile. This makes things a bit problematic when considering contributors using all different kinds of operating systems and also when it comes to testing and packaging the project.

## Acceptance Criteria

The acceptance criteria for this task is to simply migrate the project over to use the CMake tool for building and compiling the project. Any initial work, discussion, and research would be greatly appreciated.

## Additional Context

For more info on CMake: https://cmake.org/

Please read through the [Contributing to the Project](../../CONTRIBUTING.md) document before working on this project.

**Comment by batunpc** [comment]
Hey @jmakhack! I would like to take look at this

**Comment by jmakhack** [comment]
Go for it @batunpc! :)

**Comment by jmakhack** [comment]
Hi @batunpc, just checking in. Are you still looking into this?

**Comment by npranav7619** [comment]
Can I look into this

**Comment by jmakhack** [comment]
Go for it @npranav7619!

**Comment by npranav7619** [comment]
#97 

Added `CMakelists.txt` to build with `cmake`
