### ISSUE TITLE
[TASK] Investigate what is needed to get this project included in the AUR

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#72]
## Task Context

This is a research task just to see what next steps are needed for this project to get published onto the Arch User Repository. This will simply be a first step towards getting this project out there for people to more easily access, download, and install.

## Acceptance Criteria

The acceptance criteria for this task is to provide an outline of what next steps are needed to get this project onto the Arch User Repository. From there, new issues can be opened if needed to address those steps.

## Additional Context

Please read through the [Contributing to the Project](../../CONTRIBUTING.md) document before working on this project.

**Comment by GHAlmeidaDev** [comment]
hello, can you assign me some tasks in this project?

**Comment by jmakhack** [comment]
sure, I've assigned you this issue @GHAlmeidaDev

**Comment by npranav7619** [comment]
Can you assign me the task ?

**Comment by npranav7619** [comment]
Basic Needs :
        Check AUR if package already exists 
        exception to this is that the pkg should have extra-features or patches

        add a comment line to the top of the PKGBUILD file which contains information
        about the current maintainers and previous contributors

```
    # Maintainer: Your name <address at domain dot tld>
    # Maintainer: Other maintainer's name <address at domain dot tld>
    # Contributor: Previous maintainer's name <address at domain dot tld>
    # Contributor: Original submitter's name <address at domain dot tld>
```

Add the AUR Clone :
   $ `git remote add label ssh://aur@aur.archlinux.org/pkgbase.git`

Make the pakage intro `PKGBUILD`
Be sure to regenerate .SRCINFO whenever PKGBUILD metadata changes,such as pkgver() updates
otherwise the AUR will not show updated version numbers.

**Comment by jmakhack** [comment]
Thanks @npranav7619!

This info will be super useful for getting this project published to the AUR once its in a deliverable state.
Are there any useful links/docs you could also add for future reference?

**Comment by npranav7619** [comment]
I've added the References 
Let me know if i can work on building the PKGBUILD file

**Comment by jmakhack** [comment]
> I've added the References Let me know if i can work on building the PKGBUILD file

That would be great @npranav7619. The only thing is that when creating the build, a token needs to be added to the src file: https://github.com/jmakhack/myanimelist-cli/blob/587fa4fd9f96166e7c4583576ab701df2b1224cd/src/mya.c#L14.

Can I send you a token to use via twitter, email, or whatever works best for you?

**Comment by npranav7619** [comment]
yea sure you can send it though twitter 
I have my id in my profile

**Comment by jmakhack** [comment]
> yea sure you can send it though twitter 
> I have my id in my profile 

I just followed you on Twitter but it won't let me send a DM. Can you try sending me a message?

**Comment by npranav7619** [comment]
Your id ?

**Comment by jmakhack** [comment]
Thanks again for taking a look into this!
I will be closing out this issue as the research has been done and the steps to getting this on the AUR are now clear.

I will create new issues for the following next steps:
- Set up an automated Github action that generates the PKGBUILD (and potentially also .SRCINFO)
- Move the token setting logic to use an env variable so that updating the src files should no longer be necessary to set the token value
