### ISSUE TITLE
[TASK] Fix comma operator should not be used issue

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#74]
## Task Context

The Codacy Static Code Analysis reports the following error in the codebase: `The comma operator should not be used (MISRA 12.3 Rule)`

More details can be found here: https://app.codacy.com/gh/jmakhack/myanimelist-cli/issues?bid=22863233&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJFcnJvclByb25lIl19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjE1MTUyIl19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltdfV0=

## Acceptance Criteria

The acceptance criteria for this task is to fix the issues mentioned in the Codacy link. After opening a pull request, the Codacy check will automatically run to see if the issues were fixed.

## Additional Context

Please read through the [Contributing to the Project](../../CONTRIBUTING.md) document before working on this project.

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[![Discord](https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA)](https://discord.gg/RTgxfFW9mS)

**Comment by j-karthik** [comment]
@jmakhack can you please assign this issue to me?
