### ISSUE TITLE
[TASK] Add a Github action to this project to auto generate AUR requirements

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/myanimelist-cli#98]
## Task Context

Based on the findings from https://github.com/jmakhack/myanimelist-cli/issues/72#issuecomment-1590500227, certain files such as PKGBUILD need to be generated in order for this project to be added to the AUR. This task is to add an automated Github action to this repository that generates these necessities for the AUR.

There should be no need to build this from scratch as there should be existing actions on the [Github marketplace](https://github.com/marketplace?category=&query=&type=actions) that take care of this. I've included a few I've found in the `Additional Context` section.

## Acceptance Criteria

Add an automated Github action that generates the necessary items for the AUR.

If certain values are required such as maintainer name or email, feel free to simply mark those values in the PR with placeholder data and @jmakhack can edit those values to the correct values.

## Additional Context

Here are a few Github actions that may be worth looking into:
- https://github.com/marketplace/actions/arch-linux-pkgbuild-builder-action
- https://github.com/marketplace/actions/build-arch-package
- https://github.com/marketplace/actions/archlinux-pkgbuild

Please read through the [Contributing to the Project](../../CONTRIBUTING.md) document before working on this project.

**Comment by npranav7619** [comment]
Can I look into this ?

**Comment by jmakhack** [comment]
Go for it @npranav7619! :)
